let H =
      https://gitlab.horizon-haskell.net/dhall/horizon-spec/-/raw/0.10.0/horizon-spec/package.dhall

let packages =
      { BNFC = H.callHackage "BNFC" "2.9.4.1"
      , Boolean = H.callHackage "Boolean" "0.2.4"
      , Chart = H.callHackage "Chart" "1.9.4"
      , Chart-diagrams = H.callHackage "Chart-diagrams" "1.9.4"
      , Decimal = H.callHackage "Decimal" "0.5.2"
      , HTF = H.callHackage "HTF" "0.15.0.1"
      , HTTP = H.callHackage "HTTP" "4000.4.1"
      , HUnit = H.callHackage "HUnit" "1.6.2.0"
      , HaskellNet = H.callHackage "HaskellNet" "0.6.0.2"
      , Hclip = H.callHackage "Hclip" "3.0.0.4"
      , HsOpenSSL = H.callHackage "HsOpenSSL" "0.11.7.5"
      , HsYAML = H.callHackage "HsYAML" "0.2.1.1"
      , JuicyPixels = H.callHackage "JuicyPixels" "3.3.8"
      , ListLike = H.callHackage "ListLike" "4.7.8"
      , MemoTrie = H.callHackage "MemoTrie" "0.6.10"
      , MonadPrompt = H.callHackage "MonadPrompt" "1.0.0.5"
      , NumInstances = H.callHackage "NumInstances" "1.4"
      , Only = H.callHackage "Only" "0.1"
      , OpenGLRaw = H.callHackage "OpenGLRaw" "3.3.4.1"
      , PSQueue = H.callHackage "PSQueue" "1.1.1"
      , PyF = H.callHackage "PyF" "0.11.1.1"
      , QuickCheck = H.callHackage "QuickCheck" "2.14.2"
      , RSA = H.callHackage "RSA" "2.4.1"
      , SVGFonts = H.callHackage "SVGFonts" "1.8.0.1"
      , Stream = H.callHackage "Stream" "0.4.7.2"
      , Unique = H.callHackage "Unique" "0.4.7.9"
      , Unixutils = H.callHackage "Unixutils" "1.54.2"
      , X11 = H.callHackage "X11" "1.10.3"
      , X11-xft = H.callHackage "X11-xft" "0.3.4"
      , abstract-deque-tests = H.callHackage "abstract-deque-tests" "0.3"
      , active = H.callHackage "active" "0.2.0.17"
      , aeson-qq = H.callHackage "aeson-qq" "0.8.4"
      , aeson-yaml = H.callHackage "aeson-yaml" "1.1.0.1"
      , alex = H.callHackage "alex" "3.2.7.1"
      , algebraic-graphs = H.callHackage "algebraic-graphs" "0.6.1"
      , alsa-core = H.callHackage "alsa-core" "0.5.0.1"
      , alsa-mixer = H.callHackage "alsa-mixer" "0.3.0"
      , ap-normalize = H.callHackage "ap-normalize" "0.1.0.1"
      , apecs = H.callHackage "apecs" "0.9.5"
      , apply-refact = H.callHackage "apply-refact" "0.13.0.0"
      , async-timer = H.callHackage "async-timer" "0.2.0.0"
      , attoparsec-binary = H.callHackage "attoparsec-binary" "0.2"
      , attoparsec-iso8601 = H.callHackage "attoparsec-iso8601" "1.1.0.0"
      , authenticate-oauth = H.callHackage "authenticate-oauth" "1.7"
      , autodocodec-servant-multipart =
          H.callHackage "autodocodec-servant-multipart" "0.0.0.0"
      , autoexporter = H.callHackage "autoexporter" "2.0.0.8"
      , base-prelude = H.callHackage "base-prelude" "1.6.1"
      , base58-bytestring = H.callHackage "base58-bytestring" "0.1.0"
      , base64 = H.callHackage "base64" "0.4.2.4"
      , base64-bytestring = H.callHackage "base64-bytestring" "1.2.1.0"
      , base64-bytestring-type = H.callHackage "base64-bytestring-type" "1.0.1"
      , beam-core =
          H.callGit
            "https://github.com/haskell-beam/beam"
            "96e35be86dfffe4aa0b8190f7b8656e30cb36301"
            (Some "beam-core/")
      , beam-migrate =
          H.callGit
            "https://github.com/haskell-beam/beam"
            "96e35be86dfffe4aa0b8190f7b8656e30cb36301"
            (Some "beam-migrate/")
      , beam-postgres =
          H.callGit
            "https://github.com/haskell-beam/beam"
            "96e35be86dfffe4aa0b8190f7b8656e30cb36301"
            (Some "beam-postgres/")
      , beam-sqlite =
          H.callGit
            "https://github.com/haskell-beam/beam"
            "96e35be86dfffe4aa0b8190f7b8656e30cb36301"
            (Some "beam-sqlite/")
      , bech32 = H.callHackage "bech32" "1.1.2"
      , bech32-th = H.callHackage "bech32-th" "1.1.1"
      , bin = H.callHackage "bin" "0.1.3"
      , binary-orphans = H.callHackage "binary-orphans" "1.0.4.1"
      , binary-parser = H.callHackage "binary-parser" "0.5.7.3"
      , blaze-svg = H.callHackage "blaze-svg" "0.3.6.1"
      , blaze-textual = H.callHackage "blaze-textual" "0.2.3.1"
      , breakpoint = H.callHackage "breakpoint" "0.1.2.1"
      , brick = H.callHackage "brick" "1.9"
      , bytes = H.callHackage "bytes" "0.17.2"
      , bytestring-strict-builder =
          H.callHackage "bytestring-strict-builder" "0.4.5.6"
      , bytestring-tree-builder =
          H.callHackage "bytestring-tree-builder" "0.2.7.10"
      , c2hs = H.callHackage "c2hs" "0.28.8"
      , cabal-install = H.callHackage "cabal-install" "3.8.1.0"
      , cabal-install-solver = H.callHackage "cabal-install-solver" "3.8.1.0"
      , cache = H.callHackage "cache" "0.1.3.0"
      , canonical-json = H.callHackage "canonical-json" "0.6.0.1"
      , casing = H.callHackage "casing" "0.1.4.1"
      , cassava = H.callHackage "cassava" "0.5.3.0"
      , cassava-megaparsec = H.callHackage "cassava-megaparsec" "2.0.4"
      , cheapskate = H.callHackage "cheapskate" "0.1.1.2"
      , checkers = H.callHackage "checkers" "0.6.0"
      , chell = H.callHackage "chell" "0.5.0.1"
      , chell-quickcheck = H.callHackage "chell-quickcheck" "0.2.5.3"
      , circle-packing = H.callHackage "circle-packing" "0.1.0.6"
      , citeproc = H.callHackage "citeproc" "0.8.1"
      , cmark-gfm = H.callHackage "cmark-gfm" "0.2.5"
      , co-log-core = H.callHackage "co-log-core" "0.3.2.0"
      , co-log-polysemy = H.callHackage "co-log-polysemy" "0.0.1.3"
      , colourista = H.callHackage "colourista" "0.1.0.2"
      , commonmark = H.callHackage "commonmark" "0.2.2"
      , commonmark-extensions = H.callHackage "commonmark-extensions" "0.2.3.4"
      , commonmark-pandoc = H.callHackage "commonmark-pandoc" "0.2.1.3"
      , commutative-semigroups =
          H.callHackage "commutative-semigroups" "0.1.0.1"
      , compact = H.callHackage "compact" "0.2.0.0"
      , compactable =
          H.callGit
            "https://gitlab.com/fresheyeball/Compactable"
            "f63927b1e438c267f0d12f36e5b3735cfaebeeb4"
            (None H.Subdir)
      , composite-base = H.callHackage "composite-base" "0.8.2.1"
      , composite-cassava = H.callHackage "composite-cassava" "0.0.3.1"
      , composite-dhall = H.callHackage "composite-dhall" "0.1.0.1"
      , composite-lens-extra = H.callHackage "composite-lens-extra" "0.1.0.0"
      , composite-tuple = H.callHackage "composite-tuple" "0.1.2.0"
      , composition-prelude = H.callHackage "composition-prelude" "3.0.0.2"
      , concise = H.callHackage "concise" "0.1.0.1"
      , concurrent-extra = H.callHackage "concurrent-extra" "0.7.0.12"
      , conduit-combinators = H.callHackage "conduit-combinators" "1.3.0"
      , conduit-parse = H.callHackage "conduit-parse" "0.2.1.1"
      , constraints-extras = H.callHackage "constraints-extras" "0.4.0.0"
      , control-monad-free = H.callHackage "control-monad-free" "0.6.2"
      , contravariant-extras = H.callHackage "contravariant-extras" "0.3.5.3"
      , cpphs = H.callHackage "cpphs" "1.20.9.1"
      , criterion = H.callHackage "criterion" "1.6.0.0"
      , crypto-pubkey-types = H.callHackage "crypto-pubkey-types" "0.4.3"
      , cryptohash-md5 = H.callHackage "cryptohash-md5" "0.11.101.0"
      , cryptohash-sha1 = H.callHackage "cryptohash-sha1" "0.11.101.0"
      , cryptonite-conduit = H.callHackage "cryptonite-conduit" "0.2.2"
      , css-text = H.callHackage "css-text" "0.1.3.0"
      , cubicbezier = H.callHackage "cubicbezier" "0.6.0.6"
      , cursor = H.callHackage "cursor" "0.3.2.0"
      , cursor-brick = H.callHackage "cursor-brick" "0.1.0.1"
      , cursor-dirforest =
          H.callGit
            "https://github.com/NorfairKing/cursor-dirforest"
            "6ad5b168e26eb4e647df9f007d812aaf59338d40"
            (Some "cursor-dirforest/")
      , cursor-dirforest-brick =
          H.callGit
            "https://github.com/NorfairKing/cursor-dirforest"
            "6ad5b168e26eb4e647df9f007d812aaf59338d40"
            (Some "cursor-dirforest-brick/")
      , cursor-dirforest-gen =
          H.callGit
            "https://github.com/NorfairKing/cursor-dirforest"
            "6ad5b168e26eb4e647df9f007d812aaf59338d40"
            (Some "cursor-dirforest-gen/")
      , cursor-fuzzy-time = H.callHackage "cursor-fuzzy-time" "0.0.0.0"
      , cursor-gen = H.callHackage "cursor-gen" "0.4.0.0"
      , data-binary-ieee754 = H.callHackage "data-binary-ieee754" "0.4.4"
      , data-bword = H.callHackage "data-bword" "0.1.0.2"
      , data-dword = H.callHackage "data-dword" "0.3.2.1"
      , data-checked = H.callHackage "data-checked" "0.3"
      , data-endian = H.callHackage "data-endian" "0.1.1"
      , data-ordlist = H.callHackage "data-ordlist" "0.4.7.0"
      , data-serializer = H.callHackage "data-serializer" "0.3.5"
      , data-sketches = H.callHackage "data-sketches" "0.3.1.0"
      , data-sketches-core = H.callHackage "data-sketches-core" "0.1.0.0"
      , data-textual = H.callHackage "data-textual" "0.3.0.3"
      , dbus = H.callHackage "dbus" "1.2.28"
      , deepseq-generics = H.callHackage "deepseq-generics" "0.2.0.0"
      , deferred-folds = H.callHackage "deferred-folds" "0.9.18.3"
      , dense-linear-algebra = H.callHackage "dense-linear-algebra" "0.1.0.0"
      , dependent-map = H.callHackage "dependent-map" "0.4.0.0"
      , dependent-sum = H.callHackage "dependent-sum" "0.7.2.0"
      , dependent-sum-template =
          H.callHackage "dependent-sum-template" "0.1.1.1"
      , deque = H.callHackage "deque" "0.4.4"
      , deriving-aeson = H.callHackage "deriving-aeson" "0.2.9"
      , deriving-compat = H.callHackage "deriving-compat" "0.6.3"
      , dhall-docs = H.callHackage "dhall-docs" "1.0.10"
      , dhall-json = H.callHackage "dhall-json" "1.7.11"
      , dhall-nixpkgs = H.callHackage "dhall-nixpkgs" "1.0.9"
      , diagrams-contrib = H.callHackage "diagrams-contrib" "1.4.5"
      , diagrams-core = H.callHackage "diagrams-core" "1.5.1"
      , diagrams-lib = H.callHackage "diagrams-lib" "1.4.5.3"
      , diagrams-postscript = H.callHackage "diagrams-postscript" "1.5.1.1"
      , diagrams-solve = H.callHackage "diagrams-solve" "0.1.3"
      , diagrams-svg = H.callHackage "diagrams-svg" "1.4.3.1"
      , dictionary-sharing = H.callHackage "dictionary-sharing" "0.1.0.0"
      , digest = H.callHackage "digest" "0.0.1.7"
      , dimensional = H.callHackage "dimensional" "1.5"
      , direct-sqlite = H.callHackage "direct-sqlite" "2.3.28"
      , dirforest =
          H.callGit
            "https://github.com/NorfairKing/dirforest"
            "69e8ae036b047fae105c1fe990e175a7572a3eba"
            (Some "dirforest/")
      , dns = H.callHackage "dns" "4.1.0"
      , doclayout = H.callHackage "doclayout" "0.4.0.1"
      , doctemplates = H.callHackage "doctemplates" "0.11"
      , doctest = H.callHackage "doctest" "0.21.1"
      , doctest-discover = H.callHackage "doctest-discover" "0.2.0.0"
      , dom-lt = H.callHackage "dom-lt" "0.2.3"
      , double-conversion = H.callHackage "double-conversion" "2.0.4.2"
      , dual-tree = H.callHackage "dual-tree" "0.2.3.1"
      , echo = H.callHackage "echo" "0.1.4"
      , ed25519 =
          H.callGit
            "https://gitlab.homotopic.tech/horizon/adopted/ed25519"
            "faf8fe90aa1cd2492ea1e64c55f5c59fc0322210"
            (None H.Subdir)
      , edit-distance = H.callHackage "edit-distance" "0.2.2.1"
      , effectful = H.callHackage "effectful" "2.2.2.0"
      , effectful-cache =
          H.callGit
            "https://github.com/haskell-effectful/cache-effectful"
            "0a5581da7c21a05a9ab1762a6da6997090fe311d"
            (None H.Subdir)
      , effectful-core = H.callHackage "effectful-core" "2.2.2.2"
      , effectful-th = H.callHackage "effectful-th" "1.0.0.1"
      , ekg = H.callHackage "ekg" "0.4.0.15"
      , ekg-core = H.callHackage "ekg-core" "0.1.1.7"
      , ekg-json =
          H.callGit
            "https://github.com/vshabanov/ekg-json"
            "00ebe7211c981686e65730b7144fbf5350462608"
            (None H.Subdir)
      , ekg-statsd = H.callHackage "ekg-statsd" "0.2.5.0"
      , ekg-wai = H.callHackage "ekg-wai" "0.1.1.0"
      , ema = H.callHackage "ema" "0.10.0.0"
      , email-validate = H.callHackage "email-validate" "2.3.2.18"
      , emojis = H.callHackage "emojis" "0.1.2"
      , enclosed-exceptions = H.callHackage "enclosed-exceptions" "1.0.3"
      , enummapset = H.callHackage "enummapset" "0.7.1.0"
      , errors = H.callHackage "errors" "2.3.0"
      , exact-combinatorics = H.callHackage "exact-combinatorics" "0.2.0.11"
      , exact-pi = H.callHackage "exact-pi" "0.5.0.2"
      , expiring-cache-map = H.callHackage "expiring-cache-map" "0.0.6.1"
      , extended-reals = H.callHackage "extended-reals" "0.2.4.0"
      , extensible-effects = H.callHackage "extensible-effects" "5.0.0.1"
      , fast-math = H.callHackage "fast-math" "1.0.2"
      , fcf-containers = H.callHackage "fcf-containers" "0.8.2"
      , feedback = H.callHackage "feedback" "0.1.0.1"
      , file-embed = H.callHackage "file-embed" "0.0.15.0"
      , filelock = H.callHackage "filelock" "0.1.1.6"
      , filemanip = H.callHackage "filemanip" "0.3.6.3"
      , filepattern = H.callHackage "filepattern" "0.1.3"
      , filtrable = H.callHackage "filtrable" "0.1.6.0"
      , finite-field = H.callHackage "finite-field" "0.10.0"
      , finite-typelits = H.callHackage "finite-typelits" "0.1.6.0"
      , fixed = H.callHackage "fixed" "0.3"
      , floatshow = H.callHackage "floatshow" "0.2.4"
      , fmt = H.callHackage "fmt" "0.6.3.0"
      , focus = H.callHackage "focus" "1.0.3.1"
      , force-layout = H.callHackage "force-layout" "0.4.0.6"
      , foreign-store = H.callHackage "foreign-store" "0.2"
      , formatting = H.callHackage "formatting" "7.2.0"
      , foundation =
          H.callGit
            "https://gitlab.rescue.horizon-haskell.net/hackage/foundation"
            "d3136f4bb8b69e273535352620e53f2196941b35"
            (Some "foundation/")
      , fourmolu = H.callHackage "fourmolu" "0.10.1.0"
      , freer-simple = H.callHackage "freer-simple" "1.2.1.2"
      , friendly-time = H.callHackage "friendly-time" "0.4.1"
      , fsnotify = H.callHackage "fsnotify" "0.4.1.0"
      , fusion-plugin-types = H.callHackage "fusion-plugin-types" "0.1.0"
      , fuzzy = H.callHackage "fuzzy" "0.1.0.1"
      , fuzzy-time = H.callHackage "fuzzy-time" "0.2.0.3"
      , fuzzy-time-gen = H.callHackage "fuzzy-time-gen" "0.2.0.1"
      , generic-arbitrary = H.callHackage "generic-arbitrary" "1.0.1"
      , generic-data = H.callHackage "generic-data" "1.1.0.0"
      , generic-lens = H.callHackage "generic-lens" "2.2.2.0"
      , generic-lens-core = H.callHackage "generic-lens-core" "2.2.1.0"
      , generic-lens-lite = H.callHackage "generic-lens-lite" "0.1"
      , generic-monoid = H.callHackage "generic-monoid" "0.1.0.1"
      , generic-optics = H.callHackage "generic-optics" "2.2.1.0"
      , generic-optics-lite = H.callHackage "generic-optics-lite" "0.1"
      , generics-sop = H.callHackage "generics-sop" "0.5.1.3"
      , genvalidity-aeson = H.callHackage "genvalidity-aeson" "1.0.0.1"
      , genvalidity-bytestring =
          H.callHackage "genvalidity-bytestring" "1.0.0.1"
      , genvalidity-case-insensitive =
          H.callHackage "genvalidity-case-insensitive" "0.0.0.1"
      , genvalidity-containers =
          H.callHackage "genvalidity-containers" "1.0.0.1"
      , genvalidity-criterion = H.callHackage "genvalidity-criterion" "1.1.0.0"
      , genvalidity-dirforest =
          H.callGit
            "https://github.com/NorfairKing/dirforest"
            "69e8ae036b047fae105c1fe990e175a7572a3eba"
            (Some "genvalidity-dirforest/")
      , genvalidity-hspec-aeson =
          H.callHackage "genvalidity-hspec-aeson" "1.0.0.0"
      , genvalidity-hspec-optics =
          H.callHackage "genvalidity-hspec-optics" "1.0.0.0"
      , genvalidity-path = H.callHackage "genvalidity-path" "1.0.0.1"
      , genvalidity-persistent =
          H.callHackage "genvalidity-persistent" "1.0.0.1"
      , genvalidity-scientific =
          H.callHackage "genvalidity-scientific" "1.0.0.0"
      , genvalidity-sydtest = H.callHackage "genvalidity-sydtest" "1.0.0.0"
      , genvalidity-sydtest-aeson =
          H.callHackage "genvalidity-sydtest-aeson" "1.0.0.0"
      , genvalidity-sydtest-hashable =
          H.callHackage "genvalidity-sydtest-hashable" "1.0.0.0"
      , genvalidity-sydtest-lens =
          H.callHackage "genvalidity-sydtest-lens" "1.0.0.0"
      , genvalidity-sydtest-persistent =
          H.callHackage "genvalidity-sydtest-persistent" "1.0.0.0"
      , genvalidity-text = H.callHackage "genvalidity-text" "1.0.0.1"
      , genvalidity-time = H.callHackage "genvalidity-time" "1.0.0.1"
      , genvalidity-unordered-containers =
          H.callHackage "genvalidity-unordered-containers" "1.0.0.0"
      , genvalidity-uuid = H.callHackage "genvalidity-uuid" "1.0.0.1"
      , genvalidity-vector = H.callHackage "genvalidity-vector" "1.0.0.0"
      , ghc-check = H.callHackage "ghc-check" "0.5.0.8"
      , ghc-exactprint = H.callHackage "ghc-exactprint" "1.6.1.1"
      , ghc-lib-parser = H.callHackage "ghc-lib-parser" "9.4.4.20221225"
      , ghc-lib-parser-ex = H.callHackage "ghc-lib-parser-ex" "9.4.0.0"
      , ghc-tcplugins-extra = H.callHackage "ghc-tcplugins-extra" "0.4.4"
      , ghc-trace-events = H.callHackage "ghc-trace-events" "0.1.2.7"
      , ghc-typelits-knownnat = H.callHackage "ghc-typelits-knownnat" "0.7.8"
      , ghc-typelits-natnormalise =
          H.callHackage "ghc-typelits-natnormalise" "0.7.8"
      , ghcid = H.callHackage "ghcid" "0.8.8"
      , ghcide = H.callHackage "ghcide" "2.0.0.1"
      , ghcide-bench = H.callHackage "ghcide-bench" "2.0.0.1"
      , ghcide-test-utils = H.callHackage "ghcide-test-utils" "1.9.0.0"
      , githash = H.callHackage "githash" "0.1.6.3"
      , gitrev = H.callHackage "gitrev" "1.3.1"
      , gridtables = H.callHackage "gridtables" "0.1.0.0"
      , groups = H.callHackage "groups" "0.5.3"
      , gtk2hs-buildtools = H.callHackage "gtk2hs-buildtools" "0.13.10.0"
      , hackage-security = H.callHackage "hackage-security" "0.6.2.3"
      , haddock-library = H.callHackage "haddock-library" "1.11.0"
      , hashing = H.callHackage "hashing" "0.1.1.0"
      , hashtables = H.callHackage "hashtables" "1.3.1"
      , haskell-language-server =
          (H.callHackage "haskell-language-server" "2.0.0.1")
        with flags =
          [ H.CabalFlag.Disable "dynamic"
          , H.CabalFlag.Disable "ormolu"
          , H.CabalFlag.Disable "rename"
          , H.CabalFlag.Disable "stylishHaskell"
          , H.CabalFlag.Disable "eval"
          , H.CabalFlag.Disable "floskell"
          ]
      , haskell-src = H.callHackage "haskell-src" "1.0.4"
      , hasql = H.callHackage "hasql" "1.6.3"
      , hasql-explain-tests = H.callHackage "hasql-explain-tests" "0.1.0.0"
      , hasql-migration = H.callHackage "hasql-migration" "0.3.0"
      , hasql-th = H.callHackage "hasql-th" "0.4.0.18"
      , hasql-transaction = H.callHackage "hasql-transaction" "1.0.1.2"
      , hdaemonize = H.callHackage "hdaemonize" "0.5.6"
      , heaps = H.callHackage "heaps" "0.4"
      , headed-megaparsec = H.callHackage "headed-megaparsec" "0.2.1.1"
      , hedgehog-extras = H.callHackage "hedgehog-extras" "0.4.5.1"
      , hedgehog-fn = H.callHackage "hedgehog-fn" "1.0"
      , hedgehog-golden =
          H.callGit
            "https://github.com/maybe-hedgehog-later/hedgehog-golden"
            "4ab2906b3f0be5e31ee5a8585e45d43392694246"
            (None H.Subdir)
      , hedgehog-quickcheck = H.callHackage "hedgehog-quickcheck" "0.1.1"
      , heredoc = H.callHackage "heredoc" "0.2.0.0"
      , hex-text = H.callHackage "hex-text" "0.1.0.8"
      , hie-bios = H.callHackage "hie-bios" "0.12.0"
      , hie-compat = H.callHackage "hie-compat" "0.3.1.0"
      , hiedb = H.callHackage "hiedb" "0.4.3.0"
      , hinotify = H.callHackage "hinotify" "0.4.1"
      , hint =
          H.callGit
            "https://github.com/haskell-hint/hint"
            "7803c34c8ae1d83c0f7c13fe6b30fcb3abd0ac51"
            (None H.Subdir)
      , hlint = H.callHackage "hlint" "3.5"
      , hls-alternate-number-format-plugin =
          H.callHackage "hls-alternate-number-format-plugin" "2.0.0.1"
      , hls-cabal-fmt-plugin = H.callHackage "hls-cabal-fmt-plugin" "2.0.0.1"
      , hls-cabal-plugin = H.callHackage "hls-cabal-plugin" "2.0.0.1"
      , hls-call-hierarchy-plugin =
          H.callHackage "hls-call-hierarchy-plugin" "2.0.0.1"
      , hls-change-type-signature-plugin =
          H.callHackage "hls-change-type-signature-plugin" "2.0.0.1"
      , hls-class-plugin = H.callHackage "hls-class-plugin" "2.0.0.1"
      , hls-code-range-plugin = H.callHackage "hls-code-range-plugin" "2.0.0.1"
      , hls-explicit-fixity-plugin =
          H.callHackage "hls-explicit-fixity-plugin" "2.0.0.1"
      , hls-explicit-imports-plugin =
          H.callHackage "hls-explicit-imports-plugin" "2.0.0.1"
      , hls-explicit-record-fields-plugin =
          H.callHackage "hls-explicit-record-fields-plugin" "2.0.0.1"
      , hls-fourmolu-plugin = H.callHackage "hls-fourmolu-plugin" "2.0.0.1"
      , hls-gadt-plugin = H.callHackage "hls-gadt-plugin" "2.0.0.1"
      , hls-graph = H.callHackage "hls-graph" "2.0.0.1"
      , hls-hlint-plugin = H.callHackage "hls-hlint-plugin" "2.0.0.1"
      , hls-module-name-plugin =
          H.callHackage "hls-module-name-plugin" "2.0.0.1"
      , hls-overloaded-record-dot-plugin =
          H.callHackage "hls-overloaded-record-dot-plugin" "2.0.0.1"
      , hls-plugin-api = H.callHackage "hls-plugin-api" "2.0.0.1"
      , hls-pragmas-plugin = H.callHackage "hls-pragmas-plugin" "2.0.0.1"
      , hls-qualify-imported-names-plugin =
          H.callHackage "hls-qualify-imported-names-plugin" "2.0.0.1"
      , hls-refactor-plugin = H.callHackage "hls-refactor-plugin" "2.0.0.1"
      , hls-refine-imports-plugin =
          H.callHackage "hls-refine-imports-plugin" "2.0.0.1"
      , hls-retrie-plugin = H.callHackage "hls-retrie-plugin" "2.0.0.1"
      , hls-splice-plugin = H.callHackage "hls-splice-plugin" "2.0.0.1"
      , hls-test-utils = H.callHackage "hls-test-utils" "2.0.0.1"
      , hnix =
          H.callGit
            "https://github.com/haskell-nix/hnix"
            "48e962a3497893c30a749d085ebf82a8cc5cd5bd"
            (None H.Subdir)
      , hnix-store-core = H.callHackage "hnix-store-core" "0.6.1.0"
      , hnix-store-remote = H.callHackage "hnix-store-remote" "0.6.0.0"
      , hosc = H.callHackage "hosc" "0.20"
      , hp2pretty = H.callHackage "hp2pretty" "0.10"
      , hpack-dhall = H.callHackage "hpack-dhall" "0.5.7"
      , hslogger = H.callHackage "hslogger" "1.3.1.0"
      , hslua = H.callHackage "hslua" "2.3.0"
      , hslua-aeson = H.callHackage "hslua-aeson" "2.3.0.1"
      , hslua-classes = H.callHackage "hslua-classes" "2.3.0"
      , hslua-core = H.callHackage "hslua-core" "2.3.1"
      , hslua-list = H.callHackage "hslua-list" "1.1.1"
      , hslua-marshalling = H.callHackage "hslua-marshalling" "2.3.0"
      , hslua-module-doclayout = H.callHackage "hslua-module-doclayout" "1.1.0"
      , hslua-module-path = H.callHackage "hslua-module-path" "1.1.0"
      , hslua-module-system = H.callHackage "hslua-module-system" "1.1.0.1"
      , hslua-module-text = H.callHackage "hslua-module-text" "1.1.0.1"
      , hslua-module-version = H.callHackage "hslua-module-version" "1.1.0"
      , hslua-objectorientation =
          H.callHackage "hslua-objectorientation" "2.3.0"
      , hslua-packaging = H.callHackage "hslua-packaging" "2.3.0"
      , hslua-typing = H.callHackage "hslua-typing" "0.1.0"
      , hspec-attoparsec = H.callHackage "hspec-attoparsec" "0.1.0.2"
      , hspec-contrib = H.callHackage "hspec-contrib" "0.5.2"
      , hspec-expectations-lifted =
          H.callHackage "hspec-expectations-lifted" "0.10.0"
      , hspec-golden = H.callHackage "hspec-golden" "0.2.0.1"
      , hspec-golden-aeson = H.callHackage "hspec-golden-aeson" "0.9.0.0"
      , hspec-hedgehog = H.callHackage "hspec-hedgehog" "0.0.1.2"
      , hspec-megaparsec = H.callHackage "hspec-megaparsec" "2.2.0"
      , hspec-wai = H.callHackage "hspec-wai" "0.11.1"
      , hsyslog = H.callHackage "hsyslog" "5.0.2"
      , html = H.callHackage "html" "1.0.1.2"
      , html-entities = H.callHackage "html-entities" "1.1.4.6"
      , html-entity-map = H.callHackage "html-entity-map" "0.1.0.0"
      , http-api-data = H.callHackage "http-api-data" "0.5.1"
      , http-common = H.callHackage "http-common" "0.8.3.4"
      , http-media = H.callHackage "http-media" "0.8.0.0"
      , http-streams = H.callHackage "http-streams" "0.8.9.6"
      , hw-aeson = H.callHackage "hw-aeson" "0.1.8.0"
      , hw-fingertree = H.callHackage "hw-fingertree" "0.1.2.1"
      , hw-hedgehog = H.callHackage "hw-hedgehog" "0.1.1.1"
      , hw-hspec-hedgehog = H.callHackage "hw-hspec-hedgehog" "0.1.1.1"
      , hw-prim = H.callHackage "hw-prim" "0.6.3.2"
      , hxt = H.callHackage "hxt" "9.3.1.22"
      , hxt-charproperties = H.callHackage "hxt-charproperties" "9.5.0.0"
      , hxt-regex-xmlschema = H.callHackage "hxt-regex-xmlschema" "9.2.0.7"
      , hxt-unicode = H.callHackage "hxt-unicode" "9.0.2.4"
      , implicit-hie = H.callHackage "implicit-hie" "0.1.4.0"
      , implicit-hie-cradle = H.callHackage "implicit-hie-cradle" "0.5.0.1"
      , incipit-base = H.callHackage "incipit-base" "0.5.1.0"
      , incipit-core = H.callHackage "incipit-core" "0.5.1.0"
      , indexed-list-literals = H.callHackage "indexed-list-literals" "0.2.1.3"
      , indexed-profunctors = H.callHackage "indexed-profunctors" "0.1.1"
      , inline-c = H.callHackage "inline-c" "0.9.1.7"
      , insert-ordered-containers =
          H.callHackage "insert-ordered-containers" "0.2.5.2"
      , int-cast = H.callHackage "int-cast" "0.2.0.0"
      , integer-logarithms = H.callHackage "integer-logarithms" "1.0.3.1"
      , integration = H.callHackage "integration" "0.2.1"
      , intervals = H.callHackage "intervals" "0.9.2"
      , io-streams = H.callHackage "io-streams" "1.5.2.2"
      , io-streams-haproxy = H.callHackage "io-streams-haproxy" "1.0.1.0"
      , ipynb = H.callHackage "ipynb" "0.2"
      , iso8601-time = H.callHackage "iso8601-time" "0.1.5"
      , isomorphism-class = H.callHackage "isomorphism-class" "0.1.0.9"
      , iwlib = H.callHackage "iwlib" "0.1.2"
      , jira-wiki-markup = H.callHackage "jira-wiki-markup" "1.5.1"
      , jose = H.callHackage "jose" "0.10"
      , js-chart = H.callHackage "js-chart" "2.9.4.1"
      , js-dgtable = H.callHackage "js-dgtable" "0.5.2"
      , katip = H.callHackage "katip" "0.8.7.4"
      , keys = H.callHackage "keys" "3.12.3"
      , kvstore-effectful =
          H.callGit
            "https://github.com/haskell-effectful/kvstore-effectful"
            "3502825423aea3a1af9384e9d751feea4599c60b"
            (Some "kvstore-effectful/")
      , kvstore-effectful-cache =
          H.callGit
            "https://github.com/haskell-effectful/kvstore-effectful"
            "3502825423aea3a1af9384e9d751feea4599c60b"
            (Some "kvstore-effectful-cache/")
      , kvstore-effectful-spec =
          H.callGit
            "https://github.com/haskell-effectful/kvstore-effectful"
            "3502825423aea3a1af9384e9d751feea4599c60b"
            (Some "kvstore-effectful-spec/")
      , kvstore-effectful-statemap =
          H.callGit
            "https://github.com/haskell-effectful/kvstore-effectful"
            "3502825423aea3a1af9384e9d751feea4599c60b"
            (Some "kvstore-effectful-statemap/")
      , language-c = H.callHackage "language-c" "0.9.2"
      , lazy-search = H.callHackage "lazy-search" "0.1.3.0"
      , lazysmallcheck = H.callHackage "lazysmallcheck" "0.6"
      , lens-family = H.callHackage "lens-family" "2.1.2"
      , lens-family-th = H.callHackage "lens-family-th" "0.5.2.1"
      , libsodium = H.callHackage "libsodium" "1.0.18.3"
      , libsystemd-journal = H.callHackage "libsystemd-journal" "1.4.5"
      , lift-type = H.callHackage "lift-type" "0.1.1.1"
      , linear = H.callHackage "linear" "1.22"
      , linear-base = H.callHackage "linear-base" "0.3.1"
      , linear-generics = H.callHackage "linear-generics" "0.2.2"
      , list-t = H.callHackage "list-t" "1.0.5.6"
      , list-transformer = H.callHackage "list-transformer" "1.0.9"
      , lockfree-queue = H.callHackage "lockfree-queue" "0.2.4"
      , log-base = H.callHackage "log-base" "0.12.0.1"
      , log-effectful =
          H.callGit
            "https://github.com/haskell-effectful/log-effectful/"
            "910c79e10d5ac3353f2a1551103a2b63229c3f57"
            (None H.Subdir)
      , loop = H.callHackage "loop" "0.3.0"
      , lpeg = H.callHackage "lpeg" "1.0.4"
      , lrucache = H.callHackage "lrucache" "1.2.0.1"
      , lsp = H.callHackage "lsp" "1.6.0.0"
      , lsp-test = H.callHackage "lsp-test" "0.14.1.0"
      , lsp-types = H.callHackage "lsp-types" "1.6.0.0"
      , lua = H.callHackage "lua" "2.3.1"
      , lua-arbitrary = H.callHackage "lua-arbitrary" "1.0.1.1"
      , lucid = H.callHackage "lucid" "2.11.20230408"
      , lucid-alpine = H.callHackage "lucid-alpine" "0.1.0.7"
      , lucid-aria = H.callHackage "lucid-aria" "0.1.0.1"
      , lucid-svg = H.callHackage "lucid-svg" "0.7.1.1"
      , lukko = H.callHackage "lukko" "0.1.1.3"
      , lvar = H.callHackage "lvar" "0.1.0.0"
      , markdown = H.callHackage "markdown" "0.1.17.5"
      , markdown-unlit = H.callHackage "markdown-unlit" "0.5.1"
      , markov-chain-usage-model =
          H.callHackage "markov-chain-usage-model" "0.0.0"
      , matrices = H.callHackage "matrices" "0.5.0"
      , matrix = H.callHackage "matrix" "0.3.6.1"
      , mersenne-random-pure64 =
          H.callHackage "mersenne-random-pure64" "0.2.2.0"
      , mfsolve = H.callHackage "mfsolve" "0.3.2.1"
      , microlens-aeson = H.callHackage "microlens-aeson" "2.5.0"
      , microlens-ghc = H.callHackage "microlens-ghc" "0.4.14.1"
      , microlens-platform = H.callHackage "microlens-platform" "0.4.3.3"
      , microspec = H.callHackage "microspec" "0.2.1.3"
      , microstache = H.callHackage "microstache" "1.0.2.3"
      , mime-mail = H.callHackage "mime-mail" "0.5.1"
      , minio-hs = H.callHackage "minio-hs" "1.6.0"
      , mmark = H.callHackage "mmark" "0.0.7.6"
      , mod = H.callHackage "mod" "0.2.0.1"
      , modern-uri = H.callHackage "modern-uri" "0.3.6.0"
      , monad-logger = H.callHackage "monad-logger" "0.3.39"
      , monad-logger-extras = H.callHackage "monad-logger-extras" "0.1.1.1"
      , monad-loops = H.callHackage "monad-loops" "0.4.3"
      , monad-primitive = H.callHackage "monad-primitive" "0.1"
      , monad-time = H.callHackage "monad-time" "0.4.0.0"
      , monad-time-effectful = H.callHackage "monad-time-effectful" "1.0.0.0"
      , monadlist = H.callHackage "monadlist" "0.0.2"
      , monads-tf = H.callHackage "monads-tf" "0.1.0.3"
      , monoid-extras = H.callHackage "monoid-extras" "0.6.2"
      , monoid-subclasses = H.callHackage "monoid-subclasses" "1.2.3"
      , mtl-compat = H.callHackage "mtl-compat" "0.2.2"
      , mtl-prelude = H.callHackage "mtl-prelude" "2.0.3.2"
      , multiset = H.callHackage "multiset" "0.3.4.3"
      , mwc-random-monad = H.callHackage "mwc-random-monad" "0.7.3.1"
      , natural-arithmetic = H.callHackage "natural-arithmetic" "0.1.3.0"
      , natural-transformation = H.callHackage "natural-transformation" "0.4"
      , neat-interpolation = H.callHackage "neat-interpolation" "0.5.1.3"
      , net-mqtt = H.callHackage "net-mqtt" "0.8.2.5"
      , network-conduit-tls = H.callHackage "network-conduit-tls" "1.3.2"
      , network-info = H.callHackage "network-info" "0.2.1"
      , network-ip = H.callHackage "network-ip" "0.3.0.3"
      , newtype = H.callHackage "newtype" "0.2.2.0"
      , newtype-generics = H.callHackage "newtype-generics" "0.6.2"
      , nix-derivation = H.callHackage "nix-derivation" "1.1.2"
      , non-negative = H.callHackage "non-negative" "0.1.2"
      , nonempty-vector = H.callHackage "nonempty-vector" "0.2.2.0"
      , numeric-extras = H.callHackage "numeric-extras" "0.1"
      , numeric-prelude = H.callHackage "numeric-prelude" "0.4.4"
      , numtype-dk = H.callHackage "numtype-dk" "0.5.0.3"
      , odd-jobs =
          H.callGit
            "https://github.com/saurabhnanda/odd-jobs"
            "51c7443"
            (None H.Subdir)
      , one-liner = H.callHackage "one-liner" "2.1"
      , openapi3 = H.callHackage "openapi3" "3.2.3"
      , openssl-streams = H.callHackage "openssl-streams" "1.2.3.0"
      , opentelemetry = H.callHackage "opentelemetry" "0.8.0"
      , operational = H.callHackage "operational" "0.2.4.2"
      , optics = H.callHackage "optics" "0.4.2"
      , optics-core = H.callHackage "optics-core" "0.4.1"
      , optics-extra = H.callHackage "optics-extra" "0.4.2.1"
      , optics-th = H.callHackage "optics-th" "0.4.1"
      , options = H.callHackage "options" "1.2.1.1"
      , optparse-generic = H.callHackage "optparse-generic" "1.5.0"
      , optparse-simple = H.callHackage "optparse-simple" "0.1.1.4"
      , ordered-containers = H.callHackage "ordered-containers" "0.2.3"
      , pager = H.callHackage "pager" "0.1.1.0"
      , pandoc = H.callHackage "pandoc" "3.1.2"
      , pandoc-lua-marshal = H.callHackage "pandoc-lua-marshal" "0.2.2"
      , pandoc-types = H.callHackage "pandoc-types" "1.23"
      , parsec-numbers = H.callHackage "parsec-numbers" "0.1.0"
      , parsec1 = H.callHackage "parsec1" "1.0.0.8"
      , parser-combinators = H.callHackage "parser-combinators" "1.3.0"
      , parsers-megaparsec = H.callHackage "parsers-megaparsec" "0.1.0.2"
      , partial-order = H.callHackage "partial-order" "0.2.0.0"
      , password = H.callHackage "password" "3.0.2.1"
      , password-types = H.callHackage "password-types" "1.0.0.0"
      , path-pieces = H.callHackage "path-pieces" "0.2.1"
      , pcg-random = H.callHackage "pcg-random" "0.1.4.0"
      , pcre-heavy = H.callHackage "pcre-heavy" "1.0.0.3"
      , pcre2 = H.callHackage "pcre2" "2.2.1"
      , persistent = H.callHackage "persistent" "2.14.5.0"
      , persistent-postgresql = H.callHackage "persistent-postgresql" "2.13.5.2"
      , persistent-qq = H.callHackage "persistent-qq" "2.12.0.5"
      , persistent-sqlite = H.callHackage "persistent-sqlite" "2.13.1.1"
      , persistent-template = H.callHackage "persistent-template" "2.12.0.0"
      , persistent-test = H.callHackage "persistent-test" "2.13.1.3"
      , pg-entity = H.callHackage "pg-entity" "0.0.4.2"
      , pg-transact = H.callHackage "pg-transact" "0.3.2.0"
      , pg-transact-effectful =
          H.callGit
            "https://github.com/Kleidukos/pg-transact-effectful"
            "db6fa06"
            (None H.Subdir)
      , pipes = H.callHackage "pipes" "4.3.16"
      , pipes-safe = H.callHackage "pipes-safe" "2.3.4"
      , pointed = H.callHackage "pointed" "5.0.4"
      , polyparse = H.callHackage "polyparse" "1.13"
      , polysemy = H.callHackage "polysemy" "1.9.1.0"
      , polysemy-extra = H.callHackage "polysemy-extra" "0.2.1.0"
      , polysemy-kvstore = H.callHackage "polysemy-kvstore" "0.1.3.0"
      , polysemy-methodology = H.callHackage "polysemy-methodology" "0.2.2.0"
      , polysemy-path = H.callHackage "polysemy-path" "0.2.1.0"
      , polysemy-plugin = H.callHackage "polysemy-plugin" "0.4.5.0"
      , polysemy-several = H.callHackage "polysemy-several" "0.1.1.0"
      , polysemy-test = H.callHackage "polysemy-test" "0.7.0.0"
      , polysemy-time = H.callHackage "polysemy-time" "0.6.0.0"
      , polysemy-vinyl = H.callHackage "polysemy-vinyl" "0.1.5.0"
      , polysemy-zoo = H.callHackage "polysemy-zoo" "0.8.1.0"
      , port-utils = H.callHackage "port-utils" "0.2.1.0"
      , postgresql-binary = H.callHackage "postgresql-binary" "0.13.1"
      , postgres-options = H.callHackage "postgres-options" "0.2.0.0"
      , postgresql-libpq = H.callHackage "postgresql-libpq" "0.9.5.0"
      , postgresql-migration = H.callHackage "postgresql-migration" "0.2.1.6"
      , postgresql-simple = H.callHackage "postgresql-simple" "0.6.5"
      , postgresql-simple-migration =
          H.callHackage "postgresql-simple-migration" "0.1.15.0"
      , postgresql-syntax = H.callHackage "postgresql-syntax" "0.4.1"
      , pqueue = H.callHackage "pqueue" "1.4.3.0"
      , pretty-relative-time = H.callHackage "pretty-relative-time" "0.3.0.0"
      , primes = H.callHackage "primes" "0.2.1.0"
      , primitive = H.callHackage "primitive" "0.8.0.0"
      , primitive-addr = H.callHackage "primitive-addr" "0.1.0.2"
      , primitive-extras = H.callHackage "primitive-extras" "0.10.1.6"
      , primitive-offset = H.callHackage "primitive-offset" "0.2.0.0"
      , primitive-unlifted = H.callHackage "primitive-unlifted" "0.1.3.1"
      , prometheus-client = H.callHackage "prometheus-client" "1.1.0"
      , prometheus-metrics-ghc =
          H.callHackage "prometheus-metrics-ghc" "1.0.1.2"
      , prometheus-proc = H.callHackage "prometheus-proc" "0.1.5.0"
      , proteaaudio-sdl = H.callHackage "proteaaudio-sdl" "0.9.3"
      , protolude = H.callHackage "protolude" "0.3.3"
      , quickcheck-arbitrary-adt =
          H.callHackage "quickcheck-arbitrary-adt" "0.3.1.0"
      , quickcheck-assertions = H.callHackage "quickcheck-assertions" "0.3.0"
      , quickcheck-text = H.callHackage "quickcheck-text" "0.1.2.1"
      , quiet = H.callHackage "quiet" "0.2"
      , random-bytestring = H.callHackage "random-bytestring" "0.1.4"
      , random-fu = H.callHackage "random-fu" "0.3.0.1"
      , raven-haskell = H.callHackage "raven-haskell" "0.1.4.1"
      , readable = H.callHackage "readable" "0.3.1"
      , rebase = H.callHackage "rebase" "1.20"
      , recursion-schemes = H.callHackage "recursion-schemes" "5.2.2.4"
      , ref-tf = H.callHackage "ref-tf" "0.5.0.1"
      , refact = H.callHackage "refact" "0.3.0.2"
      , refined = H.callHackage "refined" "0.8.1"
      , regex-applicative = H.callHackage "regex-applicative" "0.3.4"
      , regex-compat = H.callHackage "regex-compat" "0.95.2.1"
      , regex-pcre-builtin = H.callHackage "regex-pcre-builtin" "0.95.2.3.8.44"
      , relude = H.callHackage "relude" "1.2.0.0"
      , replace-megaparsec = H.callHackage "replace-megaparsec" "1.4.5.0"
      , rerebase = H.callHackage "rerebase" "1.20"
      , resolv = H.callHackage "resolv" "0.1.2.0"
      , resource-pool = H.callHackage "resource-pool" "0.4.0.0"
      , retrie = H.callHackage "retrie" "1.2.2"
      , retry = H.callHackage "retry" "0.9.3.1"
      , rope-utf16-splay = H.callHackage "rope-utf16-splay" "0.4.0.0"
      , row-types = H.callHackage "row-types" "1.0.1.2"
      , rvar = H.callHackage "rvar" "0.3.0.2"
      , saltine = H.callHackage "saltine" "0.2.1.0"
      , sandwich = H.callHackage "sandwich" "0.1.3.2"
      , say = H.callHackage "say" "0.1.0.1"
      , scotty = H.callHackage "scotty" "0.12.1"
      , sdl2 = H.callHackage "sdl2" "2.5.5.0"
      , sdl2-gfx = H.callHackage "sdl2-gfx" "0.3.0.0"
      , sdl2-image = H.callHackage "sdl2-image" "2.1.0.0"
      , sdl2-mixer = H.callHackage "sdl2-mixer" "1.2.0.0"
      , sdl2-ttf = H.callHackage "sdl2-ttf" "2.1.3"
      , selective = H.callHackage "selective" "0.7"
      , semver = H.callHackage "semver" "0.4.0.1"
      , servant =
          H.callGit
            "https://github.com/haskell-servant/servant"
            "7ae787371333556a7b84778631ed91d1d73e8370"
            (Some "servant/")
      , servant-auth = H.callHackage "servant-auth" "0.4.1.0"
      , servant-auth-client = H.callHackage "servant-auth-client" "0.4.1.0"
      , servant-auth-server =
          H.callGit
            "https://github.com/haskell-servant/servant"
            "7ae787371333556a7b84778631ed91d1d73e8370"
            (Some "servant-auth/servant-auth-server/")
      , servant-blaze = H.callHackage "servant-blaze" "0.9.1"
      , servant-client =
          H.callGit
            "https://github.com/haskell-servant/servant"
            "7ae787371333556a7b84778631ed91d1d73e8370"
            (Some "servant-client/")
      , servant-client-core =
          H.callGit
            "https://github.com/haskell-servant/servant"
            "7ae787371333556a7b84778631ed91d1d73e8370"
            (Some "servant-client-core/")
      , servant-docs = H.callHackage "servant-docs" "0.12"
      , servant-effectful =
          H.callGit
            "https://github.com/kleidukos/servant-effectful"
            "65e3041c6cfbc315b20ad22ca18f61dda104eec8"
            (None H.Subdir)
      , servant-foreign =
          H.callGit
            "https://github.com/haskell-servant/servant"
            "7ae787371333556a7b84778631ed91d1d73e8370"
            (Some "servant-foreign/")
      , servant-lucid = H.callHackage "servant-lucid" "0.9.0.6"
      , servant-multipart = H.callHackage "servant-multipart" "0.12.1"
      , servant-multipart-api = H.callHackage "servant-multipart-api" "0.12.1"
      , servant-openapi3 = H.callHackage "servant-openapi3" "2.0.1.6"
      , servant-server =
          H.callGit
            "https://github.com/haskell-servant/servant"
            "7ae787371333556a7b84778631ed91d1d73e8370"
            (Some "servant-server/")
      , servant-static-th = H.callHackage "servant-static-th" "1.0.0.0"
      , servant-websockets = H.callHackage "servant-websockets" "2.0.0"
      , setlocale = H.callHackage "setlocale" "1.0.0.10"
      , shake = H.callHackage "shake" "0.19.7"
      , shake-bench = H.callHackage "shake-bench" "0.2.0.0"
      , shakespeare = H.callHackage "shakespeare" "2.1.0"
      , shelly = H.callHackage "shelly" "1.12.1"
      , shh = H.callHackage "shh" "0.7.2.1"
      , should-not-typecheck = H.callHackage "should-not-typecheck" "2.1.0"
      , show-combinators = H.callHackage "show-combinators" "0.2.0.0"
      , singleton-bool = H.callHackage "singleton-bool" "0.1.7"
      , singletons = H.callHackage "singletons" "3.0.2"
      , size-based = H.callHackage "size-based" "0.1.3.1"
      , skylighting = H.callHackage "skylighting" "0.13.2.1"
      , skylighting-core = H.callHackage "skylighting-core" "0.13.2.1"
      , skylighting-format-ansi = H.callHackage "skylighting-format-ansi" "0.1"
      , skylighting-format-blaze-html =
          H.callHackage "skylighting-format-blaze-html" "0.1.1"
      , skylighting-format-context =
          H.callHackage "skylighting-format-context" "0.1.0.2"
      , skylighting-format-latex =
          H.callHackage "skylighting-format-latex" "0.1"
      , slugify = H.callHackage "slugify" "0.1.0.1"
      , snap-core = H.callHackage "snap-core" "1.0.5.1"
      , snap-server = H.callHackage "snap-server" "1.1.2.1"
      , sop-core = H.callHackage "sop-core" "0.5.0.2"
      , sort = H.callHackage "sort" "1.0.0.0"
      , sorted-list = H.callHackage "sorted-list" "0.2.1.0"
      , souffle-haskell = H.callHackage "souffle-haskell" "3.5.1"
      , sqlite-simple = H.callHackage "sqlite-simple" "0.4.18.2"
      , statestack = H.callHackage "statestack" "0.3.1.1"
      , statistics = H.callHackage "statistics" "0.16.2.0"
      , statistics-linreg = H.callHackage "statistics-linreg" "0.3"
      , stm-chans = H.callHackage "stm-chans" "3.0.0.9"
      , stm-containers = H.callHackage "stm-containers" "1.2.0.2"
      , stm-hamt = H.callHackage "stm-hamt" "1.2.0.11"
      , streaming =
          H.callGit
            "https://github.com/haskell-streaming/streaming"
            "b6ec199103c078a07b3dcd197ab39020b2136426"
            (None H.Subdir)
      , streaming-binary = H.callHackage "streaming-binary" "0.3.0.1"
      , streaming-bytestring = H.callHackage "streaming-bytestring" "0.3.0"
      , streamly = H.callHackage "streamly" "0.9.0"
      , streamly-core = H.callHackage "streamly-core" "0.1.0"
      , strict-list = H.callHackage "strict-list" "0.1.7.1"
      , string-conv = H.callHackage "string-conv" "0.2.0"
      , string-conversions = H.callHackage "string-conversions" "0.4.0.1"
      , string-interpolate = H.callHackage "string-interpolate" "0.3.2.1"
      , stringsearch = H.callHackage "stringsearch" "0.3.6.6"
      , stripeapi = H.callHackage "stripeapi" "3.0.0.0"
      , sundown = H.callHackage "sundown" "0.6"
      , svg-builder = H.callHackage "svg-builder" "0.1.1"
      , swagger2 = H.callHackage "swagger2" "2.8.7"
      , system-fileio = H.callHackage "system-fileio" "0.3.16.4"
      , system-filepath = H.callHackage "system-filepath" "0.4.14"
      , tagsoup = H.callHackage "tagsoup" "0.14.8"
      , tasty-discover = H.callHackage "tasty-discover" "5.0.0"
      , tasty-hslua = H.callHackage "tasty-hslua" "1.1.0"
      , tasty-hspec = H.callHackage "tasty-hspec" "1.2.0.3"
      , tasty-lua = H.callHackage "tasty-lua" "1.1.0"
      , tasty-rerun = H.callHackage "tasty-rerun" "1.1.18"
      , tasty-wai = H.callHackage "tasty-wai" "0.1.2.0"
      , tdigest = H.callHackage "tdigest" "0.3"
      , template-haskell-compat-v0208 =
          H.callHackage "template-haskell-compat-v0208" "0.1.9.2"
      , test-framework-smallcheck =
          H.callHackage "test-framework-smallcheck" "0.2"
      , testing-feat = H.callHackage "testing-feat" "1.1.1.1"
      , testing-type-modifiers =
          H.callHackage "testing-type-modifiers" "0.1.0.1"
      , texmath = H.callHackage "texmath" "0.12.7.1"
      , text-ansi = H.callHackage "text-ansi" "0.2.1.1"
      , text-builder = H.callHackage "text-builder" "0.6.7"
      , text-builder-dev = H.callHackage "text-builder-dev" "0.3.3.2"
      , text-conversions = H.callHackage "text-conversions" "0.3.1.1"
      , text-display = H.callHackage "text-display" "0.0.4.0"
      , text-icu = H.callHackage "text-icu" "0.8.0.2"
      , text-latin1 = H.callHackage "text-latin1" "0.3.1"
      , text-printer = H.callHackage "text-printer" "0.5.0.2"
      , text-rope = H.callHackage "text-rope" "0.2"
      , th-desugar = H.callHackage "th-desugar" "1.15"
      , th-env = H.callHackage "th-env" "0.1.1"
      , th-extras = H.callHackage "th-extras" "0.0.0.6"
      , these-skinny = H.callHackage "these-skinny" "0.7.5"
      , threads = H.callHackage "threads" "0.5.1.7"
      , tidal = H.callHackage "tidal" "1.9.4"
      , tidal-link = H.callHackage "tidal-link" "1.0.1"
      , time-locale-compat = H.callHackage "time-locale-compat" "0.1.1.5"
      , time-units = H.callHackage "time-units" "1.0.0"
      , timeit = H.callHackage "timeit" "2.0"
      , timing-convenience = H.callHackage "timing-convenience" "0.1"
      , tmp-postgres = H.callHackage "tmp-postgres" "1.34.1.0"
      , torsor = H.callHackage "torsor" "0.1"
      , transformers-except = H.callHackage "transformers-except" "0.1.3"
      , tuple = H.callHackage "tuple" "0.3.0.2"
      , type-errors = H.callHackage "type-errors" "0.2.0.2"
      , type-errors-pretty = H.callHackage "type-errors-pretty" "0.0.1.2"
      , type-hint = H.callHackage "type-hint" "0.1"
      , typerep-map = H.callHackage "typerep-map" "0.6.0.0"
      , uglymemo = H.callHackage "uglymemo" "0.1.0.1"
      , unagi-chan = H.callHackage "unagi-chan" "0.4.1.4"
      , unicode-collation = H.callHackage "unicode-collation" "0.1.3.4"
      , unicode-data = H.callHackage "unicode-data" "0.4.0.1"
      , unicode-transforms = H.callHackage "unicode-transforms" "0.4.0.1"
      , universe-reverse-instances =
          H.callHackage "universe-reverse-instances" "1.1.1"
      , unix-bytestring = H.callHackage "unix-bytestring" "0.4.0"
      , unix-memory = H.callHackage "unix-memory" "0.1.2"
      , uri-bytestring = H.callHackage "uri-bytestring" "0.3.3.1"
      , url-slug = H.callHackage "url-slug" "0.1.0.0"
      , uuid = H.callHackage "uuid" "1.3.15"
      , validation = H.callHackage "validation" "1.1.2"
      , validation-selective = H.callHackage "validation-selective" "0.2.0.0"
      , validity-case-insensitive =
          H.callHackage "validity-case-insensitive" "0.0.0.0"
      , validity-path = H.callHackage "validity-path" "0.4.0.1"
      , validity-persistent = H.callHackage "validity-persistent" "0.0.0.0"
      , validity-primitive = H.callHackage "validity-primitive" "0.0.0.1"
      , validity-time = H.callHackage "validity-time" "0.5.0.0"
      , validity-uuid = H.callHackage "validity-uuid" "0.1.0.3"
      , vector-instances = H.callHackage "vector-instances" "3.4.2"
      , vector-sized = H.callHackage "vector-sized" "1.5.0"
      , vector-space = H.callHackage "vector-space" "0.16"
      , version-natural = H.callHackage "version-natural" "0.1.0.0"
      , version-natural-dhall-instance =
          H.callHackage "version-natural-dhall-instance" "0.2.0.0"
      , vinyl = H.callHackage "vinyl" "0.14.3"
      , wai-app-static = H.callHackage "wai-app-static" "3.1.7.4"
      , wai-extra = H.callHackage "wai-extra" "3.1.13.0"
      , wai-log = H.callHackage "wai-log" "0.4.0.1"
      , wai-middleware-heartbeat =
          H.callGit
            "https://github.com/flora-pm/wai-middleware-heartbeat"
            "bd7dbbe83d25c00fcd2cf5c77736af904910c596"
            (None H.Subdir)
      , wai-middleware-prometheus =
          H.callHackage "wai-middleware-prometheus" "1.0.0.1"
      , wai-middleware-static = H.callHackage "wai-middleware-static" "0.9.2"
      , wai-websockets = H.callHackage "wai-websockets" "3.0.1.2"
      , warp = H.callHackage "warp" "3.3.25"
      , warp-tls = H.callHackage "warp-tls" "3.3.6"
      , websockets = H.callHackage "websockets" "0.12.7.3"
      , wide-word = H.callHackage "wide-word" "0.1.5.0"
      , with-utf8 = H.callHackage "with-utf8" "1.0.2.4"
      , wizards = H.callHackage "wizards" "1.0.3"
      , word-compat = H.callHackage "word-compat" "0.0.6"
      , wreq = H.callHackage "wreq" "0.5.4.0"
      , wuss = H.callHackage "wuss" "2.0.1.3"
      , xml-conduit = H.callHackage "xml-conduit" "1.9.1.2"
      , xml-conduit-writer = H.callHackage "xml-conduit-writer" "0.1.1.2"
      , xml-types = H.callHackage "xml-types" "0.3.8"
      , xmlgen = H.callHackage "xmlgen" "0.6.2.2"
      , xss-sanitize = H.callHackage "xss-sanitize" "0.3.7.2"
      , zip-archive = H.callHackage "zip-archive" "0.4.3"
      , zlib-bindings = H.callHackage "zlib-bindings" "0.1.1.5"
      }

in  H.HorizonExport.MakeOverlay
      { overlayFile = "overlay.nix"
      , packagesDir = "pkgs/"
      , overlay = { compiler = "ghc-9.4.5", packages = toMap packages }
      }
